export let ZOOM_TYPE = /*#__PURE__*/function (ZOOM_TYPE) {
  ZOOM_TYPE["ZOOM_IN"] = "ZOOM_IN";
  ZOOM_TYPE["ZOOM_OUT"] = "ZOOM_OUT";
  return ZOOM_TYPE;
}({});
export let ANIMATION_VALUE = /*#__PURE__*/function (ANIMATION_VALUE) {
  ANIMATION_VALUE["SCALE"] = "SCALE";
  ANIMATION_VALUE["FOCAL_X"] = "FOCAL_X";
  ANIMATION_VALUE["FOCAL_Y"] = "FOCAL_Y";
  ANIMATION_VALUE["TRANSLATE_X"] = "TRANSLATE_X";
  ANIMATION_VALUE["TRANSLATE_Y"] = "TRANSLATE_Y";
  return ANIMATION_VALUE;
}({});
//# sourceMappingURL=types.js.map